name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Asegúrate de usar una versión compatible con tu proyecto.

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint # Personaliza según los scripts de tu proyecto.

      - name: Run tests
        run: npm test # Personaliza según tu configuración de pruebas.

      - name: Build project
        run: npm run build
